grafana:
  admin:
    existingSecret: grafana-external-secret
    userKey: grafana-admin-user
    passwordKey: grafana-admin-password

  grafana.ini:
    auth.jwt:
      enabled: true
      auto_sign_up: true
      email_claim: email
      username_claim: sub
      header_name: Authorization
      jwk_set_url: https://fake-auth.cicd/identity/v1/token/pem
      cache_ttl: 60m

  sidecar:
    skipTlsVerify: true
    dashboards:
      enabled: true
      folderAnnotation: grafana_dash_folder
      provider:
        foldersFromFilesStructure: true      
    datasources:
      enabled: true
