config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/danielnegreiros/devops-quests
      targetRevision: main

applications:
  security:
    - name: vault
    - name: external-secrets-operator
    - name: cert-manager
    - name: kube-bench-exporter
  networking:
    - name: metallb
    - name: ingress-nginx
  observability:
    - name: grafana
  cicd:
    - name: harbor
    - name: arc
    - name: arc-set-demo
