harbor:
  expose:
    tls:
      secret:
        secretName: harbor-tls-secret
    ingress:
      className: nginx
      hosts:
        core: harbor.demo.zebreje.uk
        notary: notary.demo.zebreje.uk
  externalURL: https://harbor.demo.zebreje.uk
